### ISSUE TITLE
Wrong Cmdlet

### ISSUE THREAD

**Issue by guptha1989** [MicrosoftDocs/OfficeDocs-Enterprise#794]
Note 1 says Remove-AzureAD instead of Remove-Azureaduser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223fde07-be36-8fb8-b756-4f3c8087210f
* Version Independent ID: 4d993987-b95a-62d8-0237-e4caec5908d2
* Content: [Delete user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@guptha1989 This has been corrected and updated. Thanks so much for letting us know.

**Comment by guptha1989** [comment]
It still shows as below, 

The -ObjectID parameter in the Remove-AzureAD cmdlet accepts either the account's sign-in name, also known as the User Principal Name, or the account's object ID.

I think that should be 

The -ObjectID parameter in the Remove-AzureADUser cmdlet accepts either the account's sign-in name, also known as the User Principal Name, or the account's object ID.

**Comment by JoeDavies-MSFT** [comment]
@guptha1989  It is there now. Publishing delays. Thanks again.
